-- Your SQL goes here
CREATE TABLE notes (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title VARCHAR NOT NULL,
  content TEXT NOT NULL,
  note_status INTEGER NOT NULL DEFAULT 0,
  created_at VARCHAR NOT NULL,
  updated_at VARCHAR NOT NULL
)